In [1]:
import numpy as np

Step 1: Creating a Random 10×1010 \times 1010×10 Matrix

In [4]:
# Generate a random 10x10 matrix
random_matrix_A = np.random.rand(10, 10)
print("Random 10x10 Matrix A:")
print(random_matrix_A)

Random 10x10 Matrix A:
[[0.37829579 0.05629901 0.54497638 0.48130198 0.66044226 0.30827973
  0.18006866 0.27958453 0.48561141 0.05473598]
 [0.80189183 0.17390575 0.45059608 0.92006154 0.82154709 0.43308238
  0.34770275 0.1259781  0.25067973 0.14995196]
 [0.52598239 0.5222267  0.79815632 0.89879166 0.55424525 0.54147141
  0.56088379 0.65850487 0.10071507 0.00286875]
 [0.80865439 0.95718893 0.29709425 0.79346091 0.06105668 0.5629633
  0.31786225 0.68341521 0.46933558 0.58758226]
 [0.39039025 0.50286602 0.88525948 0.11762679 0.24579866 0.14604883
  0.84637652 0.77740511 0.89862689 0.88393466]
 [0.31750872 0.94383025 0.23503371 0.83349522 0.54606543 0.71330414
  0.67231558 0.06142147 0.79956483 0.29111168]
 [0.31202767 0.58629632 0.99533497 0.14523659 0.28532014 0.11109178
  0.2893295  0.07728242 0.08513843 0.96310773]
 [0.0696384  0.28695132 0.74364473 0.0120753  0.98853581 0.34462207
  0.35266896 0.05414823 0.66781017 0.1938685 ]
 [0.8327457  0.90854251 0.03362048 0.56066766 0.012372   0

In [6]:
# Generate a second random 10x10 matrix
random_matrix_B = np.random.rand(10, 10)
print("\nRandom 10x10 Matrix B:")
print(random_matrix_B)


Random 10x10 Matrix B:
[[0.59459012 0.67305603 0.06796931 0.74944711 0.75778122 0.97141688
  0.85216664 0.93822184 0.76536447 0.88758978]
 [0.65832675 0.97219829 0.9378461  0.20019066 0.08978669 0.1650058
  0.46672292 0.59390746 0.38185979 0.17893975]
 [0.50373089 0.54434643 0.42471632 0.66556932 0.37882082 0.61406976
  0.42867403 0.86246578 0.68144729 0.35135277]
 [0.17212241 0.43061983 0.37121961 0.10542008 0.0093051  0.23621087
  0.11854844 0.81652178 0.40311329 0.07127304]
 [0.69363272 0.63426928 0.85330508 0.26699964 0.90976133 0.50580171
  0.03865295 0.06056872 0.63491066 0.10669265]
 [0.18253053 0.73911509 0.82118875 0.93612444 0.99381613 0.22818338
  0.77360105 0.46860129 0.63457771 0.28636419]
 [0.62852072 0.06231305 0.96468544 0.95164438 0.30683527 0.05143558
  0.10799223 0.55257181 0.57086545 0.17523528]
 [0.15409521 0.90043293 0.32479687 0.73543797 0.55605872 0.79641475
  0.75357893 0.12266597 0.79016095 0.09742342]
 [0.21335963 0.69060329 0.01094745 0.60970133 0.50133607 

2.2 Matrix Addition

In [7]:
# Matrix Addition
addition_result = random_matrix_A + random_matrix_B
print("\nA + B (Matrix Addition):")
print(addition_result)


A + B (Matrix Addition):
[[0.97288592 0.72935504 0.61294569 1.2307491  1.41822348 1.27969661
  1.0322353  1.21780637 1.25097588 0.94232576]
 [1.46021859 1.14610404 1.38844218 1.12025221 0.91133378 0.59808819
  0.81442567 0.71988556 0.63253952 0.3288917 ]
 [1.02971327 1.06657313 1.22287263 1.56436098 0.93306607 1.15554117
  0.98955782 1.52097065 0.78216236 0.35422151]
 [0.9807768  1.38780876 0.66831387 0.89888098 0.07036178 0.79917417
  0.43641069 1.49993698 0.87244887 0.65885531]
 [1.08402296 1.13713529 1.73856456 0.38462643 1.15555999 0.65185053
  0.88502946 0.83797383 1.53353754 0.99062731]
 [0.50003925 1.68294534 1.05622246 1.76961967 1.53988156 0.94148751
  1.44591663 0.53002277 1.43414254 0.57747587]
 [0.94054838 0.64860937 1.96002041 1.09688097 0.59215541 0.16252735
  0.39732173 0.62985422 0.65600387 1.13834301]
 [0.22373361 1.18738425 1.0684416  0.74751327 1.54459453 1.14103682
  1.10624788 0.1768142  1.45797113 0.29129192]
 [1.04610534 1.5991458  0.04456792 1.17036899 0.513708

2.3 Matrix Subtraction

In [8]:
# Matrix Subtraction
subtraction_result = random_matrix_A - random_matrix_B
print("\nA - B (Matrix Subtraction):")
print(subtraction_result)


A - B (Matrix Subtraction):
[[-0.21629433 -0.61675702  0.47700706 -0.26814513 -0.09733896 -0.66313716
  -0.67209798 -0.65863731 -0.27975305 -0.8328538 ]
 [ 0.14356508 -0.79829254 -0.48725002  0.71987088  0.7317604   0.26807658
  -0.11902017 -0.46792935 -0.13118006 -0.02898779]
 [ 0.0222515  -0.02211973  0.37344     0.23322234  0.17542442 -0.07259836
   0.13220975 -0.20396092 -0.58073223 -0.34848402]
 [ 0.63653198  0.5265691  -0.07412536  0.68804083  0.05175159  0.32675242
   0.1993138  -0.13310657  0.06622229  0.51630922]
 [-0.30324247 -0.13140326  0.0319544  -0.14937286 -0.66396266 -0.35975288
   0.80772357  0.71683639  0.26371623  0.77724202]
 [ 0.13497819  0.20471515 -0.58615504 -0.10262922 -0.4477507   0.48512076
  -0.10128547 -0.40717982  0.16498712  0.00474749]
 [-0.31649305  0.52398327  0.03064952 -0.80640778 -0.02151513  0.0596562
   0.18133726 -0.47528939 -0.48572702  0.78787245]
 [-0.08445682 -0.6134816   0.41884786 -0.72336267  0.4324771  -0.45179268
  -0.40090997 -0.068517

Matrix Multiplication

In [9]:
# Matrix Multiplication
multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print("\nA * B (Matrix Multiplication):")
print(multiplication_result)


A * B (Matrix Multiplication):
[[1.42745339 2.0963516  1.61902463 1.85343943 1.88354689 1.79543594
  1.42160867 2.07192207 1.94765977 0.92216364]
 [2.00970072 2.60378234 2.30636653 2.25360263 2.33620767 2.19541724
  1.72709776 2.76725864 2.54128168 1.43352012]
 [2.17383781 3.13442083 2.87410527 2.8594235  2.388325   2.31981682
  2.1966706  3.00445276 3.07029962 1.30112078]
 [2.31091218 3.80034281 2.89209207 2.79106526 2.35596612 2.74597344
  2.67718315 3.47295015 2.84145706 1.96598298]
 [2.61665228 3.53510096 3.03418177 3.2387942  2.50375808 3.04264357
  2.37311099 3.4358734  2.86344576 2.02229507]
 [2.36362015 3.34322427 3.27810753 2.69558867 2.37287766 2.0243188
  2.09725825 3.40127021 2.58304526 1.38499645]
 [2.12361328 2.46255681 2.45884436 1.72021338 1.5551956  2.04525492
  1.31710707 2.35354143 1.85956217 1.77287343]
 [1.84795717 2.28408938 2.24106232 2.00056215 2.14439868 1.76018602
  1.30545763 2.05145272 1.96701214 0.93977124]
 [1.8272153  2.8093438  1.90645712 2.31470883 1.6

Transpose of a Matrix

In [10]:
# Transpose of random_matrix_A
transpose_result_A = random_matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_result_A)

# Transpose of random_matrix_B
transpose_result_B = random_matrix_B.T
print("\nTranspose of Matrix B:")
print(transpose_result_B)


Transpose of Matrix A:
[[0.37829579 0.80189183 0.52598239 0.80865439 0.39039025 0.31750872
  0.31202767 0.0696384  0.8327457  0.41044354]
 [0.05629901 0.17390575 0.5222267  0.95718893 0.50286602 0.94383025
  0.58629632 0.28695132 0.90854251 0.55132693]
 [0.54497638 0.45059608 0.79815632 0.29709425 0.88525948 0.23503371
  0.99533497 0.74364473 0.03362048 0.56049738]
 [0.48130198 0.92006154 0.89879166 0.79346091 0.11762679 0.83349522
  0.14523659 0.0120753  0.56066766 0.93021442]
 [0.66044226 0.82154709 0.55424525 0.06105668 0.24579866 0.54606543
  0.28532014 0.98853581 0.012372   0.80408778]
 [0.30827973 0.43308238 0.54147141 0.5629633  0.14604883 0.71330414
  0.11109178 0.34462207 0.0143508  0.48809328]
 [0.18006866 0.34770275 0.56088379 0.31786225 0.84637652 0.67231558
  0.2893295  0.35266896 0.55402578 0.51209489]
 [0.27958453 0.1259781  0.65850487 0.68341521 0.77740511 0.06142147
  0.07728242 0.05414823 0.59182366 0.1429253 ]
 [0.48561141 0.25067973 0.10071507 0.46933558 0.89862689

1. Matrix Creation and Structure

In [ ]:
Question: Explain what a matrix is and provide an example of a 3×2 matrix. Using NumPy, write code to create this matrix.
Answer: A matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns. It is often used 
in mathematics, particularly in linear algebra, to represent data or mathematical transformations. The numbers within the matrix are called elements.

In [11]:
# Create a 3x2 matrix
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# Display the matrix
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


2. Basic Matrix Operations

Question: Given two matrices A and B, describe the conditions necessary for performing matrix addition and matrix multiplication. 
Write code to add and multiply two 5×5 matrices using NumPy.
Answer: 
Matrix Addition:
Matrix addition requires both matrices to have the same dimensions (same number of rows and columns). If matrix A is m×n and matrix B is also m×n, their sum will be a matrix of size m×n.

Matrix Multiplication:
Matrix multiplication is possible if the number of columns of A matches the number of rows of B. If A is m×n and B is n×p, the resulting matrix will be of size m×p.

In [12]:
# Create two 5x5 matrices
A = np.random.randint(1, 10, (5, 5))  
B = np.random.randint(1, 10, (5, 5))  

# Matrix Addition
C_add = A + B

# Matrix Multiplication
C_mul = np.dot(A, B)

# Display the matrices and results
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix A + B (Addition):\n", C_add)
print("\nMatrix A * B (Multiplication):\n", C_mul)


Matrix A:
 [[9 2 7 3 8]
 [3 7 9 6 9]
 [5 1 4 5 4]
 [8 1 6 5 4]
 [3 5 3 5 4]]

Matrix B:
 [[4 9 3 2 8]
 [1 8 5 1 7]
 [8 5 6 5 9]
 [3 8 9 9 9]
 [7 1 2 3 9]]

Matrix A + B (Addition):
 [[13 11 10  5 16]
 [ 4 15 14  7 16]
 [13  6 10 10 13]
 [11  9 15 14 13]
 [10  6  5  8 13]]

Matrix A * B (Multiplication):
 [[159 164 122 106 248]
 [172 185 170 139 289]
 [ 96 117  97  88 164]
 [124 154 118 104 206]
 [ 84 126 105  83 167]]


3. Transpose of a Matrix

Question: Explain the concept of matrix transposition. What effect does it have on a 3×2 matrix? Write code to create a 3×2 matrix and find its transpose.
Answer: The transpose of a matrix is obtained by swapping its rows and columns. For a matrix A of size m×n, its transpose Aᵀ will be of size n×m, where each 
element A[i][j] becomes Aᵀ[j][i].
For example, for a 3×2 matrix: 
A = [[1, 2],  
     [3, 4],  
     [5, 6]]
Its transpose Aᵀ will be:
Aᵀ = [[1, 3, 5],  
      [2, 4, 6]]

In [13]:
# Create a 3x2 matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Transpose the matrix
A_transpose = A.T

# Display the matrices
print("Original Matrix:\n", A)
print("Transposed Matrix:\n", A_transpose)


Original Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Matrix:
 [[1 3 5]
 [2 4 6]]


4. Working with Large Matrices

Question: Create a random 5×5 matrix using NumPy. Compute the sum of all elements in the matrix, then find its transpose. 
Print both the sum and the transpose of the matrix.


In [14]:
# Create a random 5x5 matrix
matrix = np.random.randint(1, 10, (5, 5))

# Compute the sum of all elements in the matrix
matrix_sum = np.sum(matrix)

# Find the transpose of the matrix
matrix_transpose = matrix.T

# Print the sum and the transpose
print("Matrix:\n", matrix)
print("\nSum of all elements in the matrix:", matrix_sum)
print("\nTranspose of the matrix:\n", matrix_transpose)


Matrix:
 [[7 7 6 4 5]
 [9 1 5 1 5]
 [8 6 4 1 8]
 [8 9 4 5 2]
 [6 4 9 9 3]]

Sum of all elements in the matrix: 136

Transpose of the matrix:
 [[7 9 8 8 6]
 [7 1 6 9 4]
 [6 5 4 4 9]
 [4 1 1 5 9]
 [5 5 8 2 3]]


Applying Matrix Operations in Context

In [15]:
# Create two random 10x10 matrices
D = np.random.randint(1, 10, (10, 10))
E = np.random.randint(1, 10, (10, 10))

# (a) Add the matrices
matrix_sum = D + E

# (b) Subtract E from D
matrix_difference = D - E

# (c) Multiply D and E using matrix multiplication
matrix_multiplication = np.dot(D, E)

# Print the results
print("Matrix D:\n", D)
print("\nMatrix E:\n", E)

print("\n(a) Matrix D + E (Addition):\n", matrix_sum)
print("\n(b) Matrix D - E (Subtraction):\n", matrix_difference)
print("\n(c) Matrix D * E (Multiplication):\n", matrix_multiplication)


Matrix D:
 [[8 3 7 7 2 5 4 3 4 6]
 [8 3 2 1 5 8 2 2 6 6]
 [7 4 7 9 1 2 4 3 6 8]
 [1 8 5 4 8 1 2 1 9 2]
 [2 7 1 3 6 1 7 5 7 5]
 [4 9 3 8 3 8 2 9 5 2]
 [1 2 3 9 4 6 3 3 3 2]
 [8 5 8 7 8 2 9 1 5 8]
 [4 1 7 4 5 5 9 8 7 6]
 [9 5 7 2 1 4 7 4 1 7]]

Matrix E:
 [[4 9 2 3 3 8 6 1 9 8]
 [9 3 7 5 2 5 6 6 7 6]
 [2 7 7 2 9 5 4 1 2 5]
 [5 4 8 4 9 1 5 8 4 6]
 [6 9 8 5 7 6 9 4 2 7]
 [8 6 3 4 3 4 8 5 9 2]
 [6 2 2 7 2 3 2 8 1 5]
 [9 4 6 5 3 1 1 5 1 9]
 [4 8 2 8 6 2 2 6 7 2]
 [3 9 8 9 9 3 2 8 3 6]]

(a) Matrix D + E (Addition):
 [[12 12  9 10  5 13 10  4 13 14]
 [17  6  9  6  7 13  8  8 13 12]
 [ 9 11 14 11 10  7  8  4  8 13]
 [ 6 12 13  8 17  2  7  9 13  8]
 [ 8 16  9  8 13  7 16  9  9 12]
 [12 15  6 12  6 12 10 14 14  4]
 [ 7  4  5 16  6  9  5 11  4  7]
 [17  9 14 12 11  3 10  6  6 17]
 [ 8  9  9 12 11  7 11 14 14  8]
 [12 14 15 11 10  7  9 12  4 13]]

(b) Matrix D - E (Subtraction):
 [[ 4 -6  5  4 -1 -3 -2  2 -5 -2]
 [-1  0 -5 -4  3  3 -4 -4 -1  0]
 [ 5 -3  0  7 -8 -3  0  2  4  3]
 [-4  4 -3  0 -1  0 