In [8]:
import numpy as np

#Generate a 3x4 random matrix
matrix_3x4 = np.random.randint(1, 21, size=(3, 4))  # Random integers between 1 and 20
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

#Solve the system using the Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

#Solve the system using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Solve Ax = b directly
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

#Verify the solution
b_check = np.dot(A, x_gaussian)
print("\nVerification (Ax = b):")
print(b_check)

# Check if the solution is correct (within a small tolerance)
if np.allclose(b_check, b):
    print("\nThe solution is verified: Ax = b")
else:
    print("\nThe solution is NOT verified: Ax != b")



Generated 3x4 Matrix:
[[16  6  6  2]
 [ 3 20  3 20]
 [ 8 19 14 13]]

Coefficient Matrix (A):
[[16  6  6]
 [ 3 20  3]
 [ 8 19 14]]

Right-hand Side Vector (b):
[ 2 20 13]

Solution using Matrix Inverse Method:
[-0.09852217  1.08866995 -0.49261084]

Solution using Gaussian Elimination (NumPy):
[-0.09852217  1.08866995 -0.49261084]

Verification (Ax = b):
[ 2. 20. 13.]

The solution is verified: Ax = b
