In [1]:
import numpy as np

# Function to execute Naive Gaussian elimination
def naive_gaussian_elimination(A):
    n = len(A)
    # Forward elimination
    for i in range(n):
        for j in range(i + 1, n):
            # Calculate the factor for elimination
            factor = A[j][i] / A[i][i]
            # Eliminate the variable from row j
            A[j] -= factor * A[i]
    return A

# Coefficient matrix A1
A1 = np.array([[4, 1, -1, -2],
               [5, 1, 2, 4],
               [6, 1, 1, 6]], dtype=float)

# Apply Naive Gaussian elimination to transform the matrix
reduced_A1 = naive_gaussian_elimination(A1.copy())

# Carry out back substitution to solve for the variables
n = A1.shape[0]
x = np.zeros(n)
for i in range(n - 1, -1, -1):
   # Perform back substitution to solve for the current variable
    x[i] = (A1[i][-1] - np.dot(A1[i][i + 1:n], x[i + 1:n])) / A1[i][i]

# Display the reduced matrix and the solution vector
print("Reduced matrix after Naive Gaussian elimination:")
print(reduced_A1)
print("Solution vector:")
print(x)


Reduced matrix after Naive Gaussian elimination:
[[ 4.    1.   -1.   -2.  ]
 [ 0.   -0.25  3.25  6.5 ]
 [ 0.    0.   -4.   -4.  ]]
Solution vector:
[ 3. -8.  6.]


In [2]:
# Function to execute Naive Gaussian elimination with chopping

def naive_gauss_elimination_with_chopping(matrix):
    n = len(matrix)

 # Perform forward elimination with chopping to 4 significant digits
    for i in range(n):
        for j in range(i + 1, n):
            factor = np.round(matrix[j][i] / matrix[i][i], 4)  # Chopping to 4 significant digits
            matrix[j] = matrix[j] - factor * matrix[i]

    return matrix

# Define the augmented matrix with coefficients and constants
augmented_matrix = np.array([[4, 1, -1, -2],
                             [5, 1, 2, 4],
                             [6, 1, 1, 6]], dtype=float)

# Execute Naive Gaussian elimination with chopping

upper_triangular_matrix = naive_gauss_elimination_with_chopping(augmented_matrix.copy())

# Execute back substitution to determine the solution vector


n = len(augmented_matrix)
solution_vector = np.zeros(n)
for i in range(n - 1, -1, -1):
    solution_vector[i] = (augmented_matrix[i][-1] - np.dot(augmented_matrix[i][i+1:n], solution_vector[i+1:n])) / augmented_matrix[i][i]

# Display the reduced matrix and the corresponding solution
print("Reduced upper triangular matrix after Naive Gauss elimination:")
print(upper_triangular_matrix)
print("Solution vector:")
print(solution_vector)

Reduced upper triangular matrix after Naive Gauss elimination:
[[ 4.    1.   -1.   -2.  ]
 [ 0.   -0.25  3.25  6.5 ]
 [ 0.    0.   -4.   -4.  ]]
Solution vector:
[ 3. -8.  6.]


In [3]:
# Function to calculate the determinant via forward elimination

def compute_determinant_with_forward_elimination(matrix):
    n = len(matrix)

    # Carry out forward elimination to transform the matrix into upper triangular form
    for i in range(n):
        for j in range(i + 1, n):
            # Compute the elimination factor for row reduction
            factor = matrix[j, i] / matrix[i, i]

            # Subtract the factor multiplied by the current row from the rows below

            matrix[j] -= factor * matrix[i]

  # The determinant is the product of the diagonal elements of the upper triangular matrix

    determinant = 1
    for i in range(n):
        determinant *= matrix[i, i]

    return determinant

# Define the coefficient matrix A3
A3 = np.array([[10, -7, 0],
               [-3, 2.099, 6],
               [5, -1, 5]], dtype=float)

# Calculate the determinant of A3 through forward elimination

determinant_A3 = compute_determinant_with_forward_elimination(A3.copy())

# Show the computed determinant
determinant_A3

-150.04999999999998

In [4]:
# The reduced triangular matrix A4 after performing forward elimination

A4_reduced = np.array([[25, 5, 1],
                       [0, -4.8, -1.56],
                       [0, 0, 0.7]], dtype=float)

# Function to calculate the determinant of a triangular matrix
def compute_determinant_triangular(matrix):
    determinant = 1
    # Multiply the diagonal elements to find the determinant
    for i in range(len(matrix)):
        determinant *= matrix[i][i]
    return determinant

# Compute the determinant of the reduced matrix A4
determinant_A4 = compute_determinant_triangular(A4_reduced)

# Output the determinant
determinant_A4

-84.0

In [5]:
def gaussian_elimination_with_partial_pivoting(A):
    n = len(A)  # Retrieve the number of rows
   # Perform forward elimination with partial pivoting
    for i in range(n):
        # Identify the row with the largest absolute value in column i for pivoting
        max_row_index = np.argmax(np.abs(A[i:n, i])) + i
        # Swap the current row with the row containing the maximum pivot element
        A[[i, max_row_index]] = A[[max_row_index, i]]

       # Eliminate the entries below the pivot in column i

        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j] = A[j] - factor * A[i]

    return A

def back_substitution(A):
    n = len(A)
    x = np.zeros(n)

   # Begin with the last row and work upwards to perform back substitution

    for i in range(n-1, -1, -1):
        x[i] = (A[i, -1] - np.dot(A[i, i+1:n], x[i+1:n])) / A[i, i]

    return x

# Example augmented matrix (4x4 matrix with the right-hand side in the last column)
A5 = np.array([[4, 1, -1, -2],
               [5, 1, 2, 4],
               [6, 1, 1, 6]], dtype=float)

# Apply Gaussian elimination with partial pivoting
reduced_A5 = gaussian_elimination_with_partial_pivoting(A5.copy())

# Solve the system by performing back substitution
solution = back_substitution(reduced_A5)

# Display the reduced matrix and the solution
print("Reduced matrix after Gaussian elimination with partial pivoting:")
print(reduced_A5)
print("Solution vector:")
print(solution)

Reduced matrix after Gaussian elimination with partial pivoting:
[[ 6.          1.          1.          6.        ]
 [ 0.          0.33333333 -1.66666667 -6.        ]
 [ 0.          0.          2.          2.        ]]
Solution vector:
[  3. -13.   1.]


In [6]:
# Function to perform Gaussian elimination with partial pivoting and rounding to four significant digits
def gaussian_elimination_with_pivoting_chopping(A):
    n = len(A)

    # Perform forward elimination with partial pivoting
    for i in range(n):
        # Find the row with the largest absolute value in column i for pivoting
        max_row_index = np.argmax(np.abs(A[i:n, i])) + i
        A[[i, max_row_index]] = A[[max_row_index, i]]  # Swap the rows

        # Eliminate elements below the pivot
        for j in range(i + 1, n):
            # Compute the factor to eliminate the variable and chop to four significant digits
            factor = np.round(A[j][i] / A[i][i], 4)
            A[j] -= factor * A[i]  # Update row j
    return A

# Matrix of coefficients for the system of equations
A = np.array([[4 , 1 , -1 , -2],
              [5 , 1 , 2 , 4],
              [6 , 1 , 1 , 6]], dtype=float)

# Execute Gaussian elimination with partial pivoting and rounding to four significant digits
reduced_matrix = gaussian_elimination_with_pivoting_chopping(A.copy())

# Perform back substitution to compute the values of the variables

n = len(A)
solution = np.zeros(n)
for i in range(n-1, -1, -1):
    solution[i] = (reduced_matrix[i][-1] - np.dot(reduced_matrix[i][i+1:n], solution[i+1:n])) / reduced_matrix[i][i]

# Display the reduced matrix and the solution vector
print("Reduced matrix after Gaussian elimination with partial pivoting:")
print(reduced_matrix)
print("Solution vector:")
print(solution)


Reduced matrix after Gaussian elimination with partial pivoting:
[[ 6.00000000e+00  1.00000000e+00  1.00000000e+00  6.00000000e+00]
 [-2.00000000e-04  3.33300000e-01 -1.66670000e+00 -6.00020000e+00]
 [ 3.00040000e-04 -1.66600000e-05  2.00038334e+00  2.00150004e+00]]
Solution vector:
[  2.99974173 -12.99900863   1.00055824]
